
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Sat Dec 01 2018 13:38:53 GMT+0100 (CET).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class Frontpage extends ContentItem {
    public heroHeadline: Fields.TextField;
    public heroCta: Fields.TextField;
    public heroLink: ContentItem[];
    public heroDescription: Fields.TextField;
    public heroImage: Fields.AssetsField;
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'hero_headline') {
                    return 'heroHeadline';
                }
                if (fieldName === 'hero_cta') {
                    return 'heroCta';
                }
                if (fieldName === 'hero_link') {
                    return 'heroLink';
                }
                if (fieldName === 'hero_description') {
                    return 'heroDescription';
                }
                if (fieldName === 'hero_image') {
                    return 'heroImage';
                }
                return fieldName;
            })
        });
    }
}
