
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Sun Dec 02 2018 10:58:38 GMT+0100 (CET).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class Frontpage extends ContentItem {
    public heroHeadline: Fields.TextField;
    public heroCtaText: Fields.TextField;
    public heroCtaLink: ContentItem[];
    public heroDescription: Fields.TextField;
    public heroImage: Fields.AssetsField;
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'hero_headline') {
                    return 'heroHeadline';
                }
                if (fieldName === 'hero_cta_text') {
                    return 'heroCtaText';
                }
                if (fieldName === 'hero_cta_link') {
                    return 'heroCtaLink';
                }
                if (fieldName === 'hero_description') {
                    return 'heroDescription';
                }
                if (fieldName === 'hero_image') {
                    return 'heroImage';
                }
                return fieldName;
            })
        });
    }
}
