
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Dec 03 2018 08:44:47 GMT+0100 (CET).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class ProductPage extends ContentItem {
    public sections: ContentItem[];
    public headline: Fields.TextField;
    public description: Fields.TextField;
    public boxes: ContentItem[];
}
