
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Sun Dec 02 2018 15:23:43 GMT+0100 (CET).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class Step extends ContentItem {
    public image: Fields.AssetsField;
    public headline: Fields.TextField;
    public description: Fields.TextField;
}
